version = 1

[python]
version = "3.14"

[validation]
checks = ["ruff", "ruff-format", "mypy", "pytest", "docker-compose", "pre-commit"]

[build]
python_package = true

[container]
publish = true
image_name = "template-fastapi-service"

[release]
semantic_release = true
